"use client";

import { useEffect } from "react";

type Language = "English" | "Arabic" | "German" | "French" | "Spanish";

const languageCodes: Record<Language, string> = {
  English: "en",
  Arabic: "ar",
  German: "de",
  French: "fr",
  Spanish: "es",
};

const common: Record<Exclude<Language, "English">, Record<string, string>> = {
  Arabic: {
    Platform: "المنصة",
    Accounting: "المحاسبة",
    Pricing: "الأسعار",
    FAQ: "الأسئلة",
    Login: "تسجيل الدخول",
    Register: "التسجيل",
    Dashboard: "لوحة التحكم",
    "Start Pro Trial": "ابدأ تجربة Pro",
    "Create your workspace": "أنشئ مساحة العمل",
    "Explore platform": "استكشف المنصة",
    "Global company management software": "برنامج عالمي لإدارة الشركات",
    "Manage any business, anywhere.": "أدر أي عمل، في أي مكان.",
    "Everything your company needs to operate.": "كل ما تحتاجه شركتك للتشغيل.",
    "Finance and accounting": "المالية والمحاسبة",
    "Know where the money is going.": "اعرف أين تذهب الأموال.",
    Workflow: "سير العمل",
    "From first customer to final report.": "من أول عميل إلى آخر تقرير.",
    "Plans that match your operating stage.": "خطط تناسب مرحلة عملك.",
    "Security and global readiness": "الأمان والاستعداد العالمي",
    "Built for multi-company SaaS from the start.": "مصمم لمنصة شركات متعددة منذ البداية.",
    "Questions before you start?": "أسئلة قبل البدء؟",
    "Ready to start": "جاهز للبدء",
    "Account": "الحساب",
    "Legal": "القانوني",
    "Contact Us": "اتصل بنا",
    "Privacy Policy": "سياسة الخصوصية",
    "Terms of Service": "شروط الخدمة",
    "Refund Policy": "سياسة الاسترداد",
    "Cookie Policy": "سياسة ملفات تعريف الارتباط",
    "Monthly": "شهري",
    "Yearly": "سنوي",
    "Sign up first": "سجّل أولاً",
    "No free trial": "لا توجد تجربة مجانية",
    "3-day free trial": "تجربة مجانية 3 أيام",
    "Yearly billing includes 2 months free.": "الفوترة السنوية تشمل شهرين مجاناً.",
    "Switch to yearly to see annual pricing.": "بدّل إلى السنوي لعرض السعر السنوي.",
    Customers: "العملاء",
    Employees: "الموظفون",
    Bookings: "الحجوزات",
    Tasks: "المهام",
    Invoices: "الفواتير",
    Payments: "المدفوعات",
    Expenses: "المصروفات",
    Documents: "المستندات",
    Inventory: "المخزون",
    Reports: "التقارير",
    Branches: "الفروع",
    Permissions: "الصلاحيات",
    Settings: "الإعدادات",
    Subscription: "الاشتراك",
    "Business Dashboard": "لوحة إدارة الأعمال",
    "Comvexa Workspace": "مساحة عمل Comvexa",
    "Global workspace ready": "مساحة العمل جاهزة",
    "Sign out": "تسجيل الخروج",
    "Workspace module": "وحدة مساحة العمل",
    Refresh: "تحديث",
    "Total records": "إجمالي السجلات",
    "Visible now": "المعروضة الآن",
    "Required fields": "الحقول المطلوبة",
    "Create record": "إنشاء سجل",
    "Add new entry": "إضافة إدخال جديد",
    Records: "السجلات",
    Required: "مطلوب",
    Actions: "الإجراءات",
    Delete: "حذف",
    "No records yet": "لا توجد سجلات بعد",
    Name: "الاسم",
    Email: "البريد الإلكتروني",
    Phone: "الهاتف",
    Address: "العنوان",
    Notes: "ملاحظات",
    Status: "الحالة",
    Salary: "الراتب",
    Position: "المنصب",
    Department: "القسم",
    Nationality: "الجنسية",
    "Employee ID": "رقم الموظف",
    "ID card number": "رقم البطاقة",
    "ID card expiry": "انتهاء البطاقة",
    "Emergency contact name": "اسم جهة الطوارئ",
    "Emergency contact phone": "هاتف جهة الطوارئ",
    "Display language": "لغة العرض",
    Currency: "العملة",
    "Module Visibility": "إظهار الوحدات",
    "Company Identity": "هوية الشركة",
    Appearance: "المظهر",
    "Workflow Controls": "إعدادات سير العمل",
  },
  German: {
    Platform: "Plattform",
    Accounting: "Buchhaltung",
    Pricing: "Preise",
    FAQ: "FAQ",
    Login: "Anmelden",
    Register: "Registrieren",
    Dashboard: "Dashboard",
    "Start Pro Trial": "Pro-Test starten",
    "Create your workspace": "Arbeitsbereich erstellen",
    "Explore platform": "Plattform ansehen",
    "Manage any business, anywhere.": "Jedes Unternehmen überall verwalten.",
    Customers: "Kunden",
    Employees: "Mitarbeiter",
    Bookings: "Buchungen",
    Tasks: "Aufgaben",
    Invoices: "Rechnungen",
    Payments: "Zahlungen",
    Expenses: "Ausgaben",
    Documents: "Dokumente",
    Inventory: "Inventar",
    Reports: "Berichte",
    Branches: "Filialen",
    Permissions: "Berechtigungen",
    Settings: "Einstellungen",
    Subscription: "Abonnement",
    "Business Dashboard": "Business-Dashboard",
    "Global workspace ready": "Globaler Arbeitsbereich bereit",
    "Sign out": "Abmelden",
    Monthly: "Monatlich",
    Yearly: "Jährlich",
    "Sign up first": "Zuerst registrieren",
    Refresh: "Aktualisieren",
    Records: "Datensätze",
    Required: "Erforderlich",
    Actions: "Aktionen",
    Delete: "Löschen",
    Name: "Name",
    Email: "E-Mail",
    Phone: "Telefon",
    Address: "Adresse",
    Notes: "Notizen",
    Status: "Status",
    Salary: "Gehalt",
    Position: "Position",
    Department: "Abteilung",
    Nationality: "Nationalität",
    Currency: "Währung",
  },
  French: {
    Platform: "Plateforme",
    Accounting: "Comptabilité",
    Pricing: "Tarifs",
    FAQ: "FAQ",
    Login: "Connexion",
    Register: "Inscription",
    Dashboard: "Tableau de bord",
    "Start Pro Trial": "Essai Pro",
    "Create your workspace": "Créer votre espace",
    "Explore platform": "Explorer la plateforme",
    "Manage any business, anywhere.": "Gérez toute entreprise, partout.",
    Customers: "Clients",
    Employees: "Employés",
    Bookings: "Réservations",
    Tasks: "Tâches",
    Invoices: "Factures",
    Payments: "Paiements",
    Expenses: "Dépenses",
    Documents: "Documents",
    Inventory: "Inventaire",
    Reports: "Rapports",
    Branches: "Succursales",
    Permissions: "Autorisations",
    Settings: "Paramètres",
    Subscription: "Abonnement",
    "Business Dashboard": "Tableau de bord",
    "Global workspace ready": "Espace global prêt",
    "Sign out": "Se déconnecter",
    Monthly: "Mensuel",
    Yearly: "Annuel",
    "Sign up first": "S'inscrire d'abord",
    Refresh: "Actualiser",
    Records: "Enregistrements",
    Required: "Requis",
    Actions: "Actions",
    Delete: "Supprimer",
    Name: "Nom",
    Email: "E-mail",
    Phone: "Téléphone",
    Address: "Adresse",
    Notes: "Notes",
    Status: "Statut",
    Salary: "Salaire",
    Position: "Poste",
    Department: "Département",
    Nationality: "Nationalité",
    Currency: "Devise",
  },
  Spanish: {
    Platform: "Plataforma",
    Accounting: "Contabilidad",
    Pricing: "Precios",
    FAQ: "FAQ",
    Login: "Iniciar sesión",
    Register: "Registro",
    Dashboard: "Panel",
    "Start Pro Trial": "Iniciar prueba Pro",
    "Create your workspace": "Crear espacio",
    "Explore platform": "Explorar plataforma",
    "Manage any business, anywhere.": "Gestiona cualquier negocio, en cualquier lugar.",
    Customers: "Clientes",
    Employees: "Empleados",
    Bookings: "Reservas",
    Tasks: "Tareas",
    Invoices: "Facturas",
    Payments: "Pagos",
    Expenses: "Gastos",
    Documents: "Documentos",
    Inventory: "Inventario",
    Reports: "Informes",
    Branches: "Sucursales",
    Permissions: "Permisos",
    Settings: "Configuración",
    Subscription: "Suscripción",
    "Business Dashboard": "Panel de negocio",
    "Global workspace ready": "Espacio global listo",
    "Sign out": "Cerrar sesión",
    Monthly: "Mensual",
    Yearly: "Anual",
    "Sign up first": "Registrarse primero",
    Refresh: "Actualizar",
    Records: "Registros",
    Required: "Obligatorio",
    Actions: "Acciones",
    Delete: "Eliminar",
    Name: "Nombre",
    Email: "Correo",
    Phone: "Teléfono",
    Address: "Dirección",
    Notes: "Notas",
    Status: "Estado",
    Salary: "Salario",
    Position: "Cargo",
    Department: "Departamento",
    Nationality: "Nacionalidad",
    Currency: "Moneda",
  },
};

Object.assign(common.Arabic, {
  "Comvexa gives companies one workspace for customers, employees, bookings, tasks, invoices, payments, expenses, documents, reports, branches, inventory, and daily operations.": "تمنح Comvexa الشركات مساحة عمل واحدة لإدارة العملاء والموظفين والحجوزات والمهام والفواتير والمدفوعات والمصروفات والمستندات والتقارير والفروع والمخزون والعمليات اليومية.",
  "Global-ready": "جاهز عالمياً",
  "Works for teams, branches, and markets worldwide.": "يناسب الفرق والفروع والأسواق في مختلف الدول.",
  "Operations-first": "مصمم للعمليات",
  "Customers, staff, work, invoices, and reports together.": "العملاء والموظفون والعمل والفواتير والتقارير في مكان واحد.",
  "Plan controlled": "تحكم حسب الخطة",
  "Only unlock the modules included in each subscription.": "لا تظهر إلا الوحدات المتاحة ضمن الاشتراك المحدد.",
  "Pro trial": "تجربة Pro",
  "Try Pro for 3 days before continuing monthly.": "جرّب Pro لمدة 3 أيام قبل المتابعة باشتراك شهري.",
  "Everything your company needs to operate.": "كل ما تحتاجه شركتك لتعمل بكفاءة.",
  "Comvexa is not a single-purpose tool. It combines operations, finance, documents, people, inventory, reports, and company settings in one organized workspace.": "Comvexa ليست أداة لغرض واحد؛ فهي تجمع العمليات والمالية والمستندات والموظفين والمخزون والتقارير وإعدادات الشركة في مساحة عمل منظمة.",
  "Service companies": "شركات الخدمات",
  "Retail stores": "متاجر التجزئة",
  Agencies: "الوكالات",
  Clinics: "العيادات",
  Contractors: "المقاولون",
  Salons: "الصالونات",
  "Maintenance teams": "فرق الصيانة",
  "Field operations": "العمليات الميدانية",
  "Services & Products": "الخدمات والمنتجات",
  "Staff Schedules": "جداول الموظفين",
  "Recurring Invoices": "الفواتير المتكررة",
  "Supplier Bills": "فواتير الموردين",
  "WhatsApp Templates": "قوالب واتساب",
  "Company settings": "إعدادات الشركة",
  "Company Identity": "هوية الشركة",
  "Regional and Accounting Defaults": "الإعدادات الإقليمية والمحاسبية الافتراضية",
  "Workflow Controls": "ضوابط سير العمل",
  "Module Visibility": "إظهار الوحدات",
  "Display name": "اسم العرض",
  Industry: "القطاع",
  "Default start page": "صفحة البداية الافتراضية",
  "Display language": "لغة العرض",
  "Accent color": "لون التمييز",
  "Dashboard style": "نمط لوحة التحكم",
  "Sidebar style": "نمط القائمة الجانبية",
  Density: "كثافة العرض",
  "Corner style": "شكل الزوايا",
  Timezone: "المنطقة الزمنية",
  "Date format": "تنسيق التاريخ",
  "Invoice prefix": "بادئة الفاتورة",
  "Tax label": "تسمية الضريبة",
  "Default tax rate": "نسبة الضريبة الافتراضية",
  "Show setup checklist": "إظهار قائمة الإعداد",
  "Show finance pulse": "إظهار نبض المالية",
  "Email reminders": "تذكيرات البريد الإلكتروني",
  "WhatsApp templates": "قوالب واتساب",
  "Payment terms": "شروط الدفع",
  "Reminder tone": "نبرة التذكير",
  "Save customization": "حفظ التخصيص",
  "Confirm saved settings": "تأكيد الإعدادات المحفوظة",
  "Saved automatically": "تم الحفظ تلقائياً",
  "Choose your plan": "اختر خطتك",
  "Step 1 of 2": "الخطوة 1 من 2",
  "Choose plan": "اختر الخطة",
  "Plan selected": "تم اختيار الخطة",
  "Plan summary": "ملخص الخطة",
  "Due today": "المستحق اليوم",
  "Due on payment page": "المستحق في صفحة الدفع",
  "Open dashboard": "فتح لوحة التحكم",
  "Start 3-day trial": "بدء تجربة 3 أيام",
  "Continue to payment": "المتابعة إلى الدفع",
  "Business intelligence": "ذكاء الأعمال",
  "Executive snapshot": "ملخص تنفيذي",
  "Current profit / loss": "الربح / الخسارة الحالية",
  "Recorded income": "الدخل المسجل",
  "Profit / loss": "الربح / الخسارة",
  "Cash flow": "التدفق النقدي",
  "Invoice total": "إجمالي الفواتير",
  "Unpaid invoices": "الفواتير غير المدفوعة",
  "Supplier bills": "فواتير الموردين",
  "Tax tracked": "الضريبة المتتبعة",
  "Collection rate": "معدل التحصيل",
  "Operating load": "عبء العمليات",
  Contact: "التواصل",
  Support: "الدعم",
  Billing: "الفوترة",
  Privacy: "الخصوصية",
  "Send a request": "إرسال طلب",
  "Tell us what you need": "أخبرنا بما تحتاجه",
  Topic: "الموضوع",
  Message: "الرسالة",
  "Save request": "حفظ الطلب",
  "Response time": "وقت الاستجابة",
});

Object.assign(common.German, {
  "Comvexa gives companies one workspace for customers, employees, bookings, tasks, invoices, payments, expenses, documents, reports, branches, inventory, and daily operations.": "Comvexa bietet Unternehmen einen zentralen Arbeitsbereich für Kunden, Mitarbeitende, Buchungen, Aufgaben, Rechnungen, Zahlungen, Ausgaben, Dokumente, Berichte, Filialen, Inventar und den täglichen Betrieb.",
  "Global company management software": "Globale Unternehmenssoftware",
  "Everything your company needs to operate.": "Alles, was Ihr Unternehmen für den Betrieb benötigt.",
  "Finance and accounting": "Finanzen und Buchhaltung",
  "Know where the money is going.": "Behalten Sie jederzeit den Überblick über Ihre Finanzen.",
  Workflow: "Ablauf",
  "From first customer to final report.": "Vom ersten Kunden bis zum finalen Bericht.",
  "Plans that match your operating stage.": "Tarife passend zu Ihrer Unternehmensphase.",
  "Security and global readiness": "Sicherheit und internationale Einsatzbereitschaft",
  "Built for multi-company SaaS from the start.": "Von Anfang an für Multi-Company-SaaS entwickelt.",
  "Questions before you start?": "Noch Fragen vor dem Start?",
  "Ready to start": "Bereit zum Start",
  Account: "Konto",
  Legal: "Rechtliches",
  "Contact Us": "Kontakt",
  "Privacy Policy": "Datenschutzerklärung",
  "Terms of Service": "Nutzungsbedingungen",
  "Refund Policy": "Rückerstattungsrichtlinie",
  "Cookie Policy": "Cookie-Richtlinie",
  "No free trial": "Keine kostenlose Testphase",
  "3-day free trial": "3 Tage kostenlos testen",
  "Yearly billing includes 2 months free.": "Bei jährlicher Abrechnung sind 2 Monate kostenlos enthalten.",
  "Switch to yearly to see annual pricing.": "Wechseln Sie zu jährlich, um die Jahrespreise zu sehen.",
  "Global-ready": "Weltweit einsatzbereit",
  "Operations-first": "Betriebsorientiert",
  "Plan controlled": "Tarifgesteuert",
  "Try Pro for 3 days before continuing monthly.": "Testen Sie Pro 3 Tage lang, bevor Sie monatlich fortfahren.",
  "Services & Products": "Services und Produkte",
  "Staff Schedules": "Dienstpläne",
  "Recurring Invoices": "Wiederkehrende Rechnungen",
  "Supplier Bills": "Lieferantenrechnungen",
  "WhatsApp Templates": "WhatsApp-Vorlagen",
  "Company Identity": "Unternehmensidentität",
  Appearance: "Darstellung",
  "Regional and Accounting Defaults": "Regionale und buchhalterische Vorgaben",
  "Workflow Controls": "Workflow-Steuerung",
  "Module Visibility": "Modulsichtbarkeit",
  "Display name": "Anzeigename",
  Industry: "Branche",
  "Default start page": "Standard-Startseite",
  "Display language": "Anzeigesprache",
  "Accent color": "Akzentfarbe",
  "Dashboard style": "Dashboard-Stil",
  "Sidebar style": "Seitenleisten-Stil",
  Density: "Dichte",
  "Corner style": "Eckenstil",
  Timezone: "Zeitzone",
  "Date format": "Datumsformat",
  "Invoice prefix": "Rechnungspräfix",
  "Tax label": "Steuerbezeichnung",
  "Default tax rate": "Standard-Steuersatz",
  "Show setup checklist": "Einrichtungs-Checkliste anzeigen",
  "Show finance pulse": "Finanzübersicht anzeigen",
  "Email reminders": "E-Mail-Erinnerungen",
  "Payment terms": "Zahlungsbedingungen",
  "Reminder tone": "Ton der Erinnerung",
  "Choose your plan": "Tarif auswählen",
  "Step 1 of 2": "Schritt 1 von 2",
  "Choose plan": "Tarif wählen",
  "Plan selected": "Tarif ausgewählt",
  "Plan summary": "Tarifübersicht",
  "Due today": "Heute fällig",
  "Due on payment page": "Fällig auf der Zahlungsseite",
  "Open dashboard": "Dashboard öffnen",
  "Start 3-day trial": "3-Tage-Test starten",
  "Continue to payment": "Weiter zur Zahlung",
  "Business intelligence": "Business Intelligence",
  "Executive snapshot": "Management-Überblick",
  "Current profit / loss": "Aktueller Gewinn / Verlust",
  "Recorded income": "Erfasste Einnahmen",
  "Profit / loss": "Gewinn / Verlust",
  "Cash flow": "Cashflow",
  "Invoice total": "Rechnungssumme",
  "Unpaid invoices": "Offene Rechnungen",
  "Supplier bills": "Lieferantenrechnungen",
  "Tax tracked": "Erfasste Steuer",
  "Collection rate": "Inkassoquote",
  "Operating load": "Operative Auslastung",
  Contact: "Kontakt",
  Support: "Support",
  Billing: "Abrechnung",
  Privacy: "Datenschutz",
  "Send a request": "Anfrage senden",
  "Tell us what you need": "Sagen Sie uns, was Sie benötigen",
  Topic: "Thema",
  Message: "Nachricht",
  "Save request": "Anfrage speichern",
  "Response time": "Antwortzeit",
  "Employee ID": "Mitarbeiter-ID",
  "ID card number": "Ausweisnummer",
  "ID card expiry": "Ausweis gültig bis",
  "Emergency contact name": "Notfallkontakt",
  "Emergency contact phone": "Telefon des Notfallkontakts",
});

Object.assign(common.French, {
  "Comvexa gives companies one workspace for customers, employees, bookings, tasks, invoices, payments, expenses, documents, reports, branches, inventory, and daily operations.": "Comvexa offre aux entreprises un espace de travail unique pour gérer clients, employés, réservations, tâches, factures, paiements, dépenses, documents, rapports, succursales, inventaire et opérations quotidiennes.",
  "Global company management software": "Logiciel mondial de gestion d'entreprise",
  "Everything your company needs to operate.": "Tout ce dont votre entreprise a besoin pour fonctionner.",
  "Finance and accounting": "Finance et comptabilité",
  "Know where the money is going.": "Gardez une vision claire de vos flux financiers.",
  Workflow: "Flux de travail",
  "From first customer to final report.": "Du premier client au rapport final.",
  "Plans that match your operating stage.": "Des forfaits adaptés à votre stade d'activité.",
  "Security and global readiness": "Sécurité et préparation internationale",
  "Built for multi-company SaaS from the start.": "Conçu dès le départ pour un SaaS multi-entreprises.",
  "Questions before you start?": "Des questions avant de commencer ?",
  "Ready to start": "Prêt à démarrer",
  Account: "Compte",
  Legal: "Mentions légales",
  "Contact Us": "Contactez-nous",
  "Privacy Policy": "Politique de confidentialité",
  "Terms of Service": "Conditions d'utilisation",
  "Refund Policy": "Politique de remboursement",
  "Cookie Policy": "Politique relative aux cookies",
  "No free trial": "Pas d'essai gratuit",
  "3-day free trial": "Essai gratuit de 3 jours",
  "Yearly billing includes 2 months free.": "La facturation annuelle inclut 2 mois gratuits.",
  "Switch to yearly to see annual pricing.": "Passez à l'annuel pour voir le prix annuel.",
  "Global-ready": "Prêt pour l'international",
  "Operations-first": "Axé sur les opérations",
  "Plan controlled": "Contrôlé par forfait",
  "Try Pro for 3 days before continuing monthly.": "Essayez Pro pendant 3 jours avant de poursuivre en mensuel.",
  "Services & Products": "Services et produits",
  "Staff Schedules": "Plannings du personnel",
  "Recurring Invoices": "Factures récurrentes",
  "Supplier Bills": "Factures fournisseurs",
  "WhatsApp Templates": "Modèles WhatsApp",
  "Company Identity": "Identité de l'entreprise",
  Appearance: "Apparence",
  "Regional and Accounting Defaults": "Paramètres régionaux et comptables",
  "Workflow Controls": "Contrôles du workflow",
  "Module Visibility": "Visibilité des modules",
  "Display name": "Nom affiché",
  Industry: "Secteur",
  "Default start page": "Page d'accueil par défaut",
  "Display language": "Langue d'affichage",
  "Accent color": "Couleur d'accent",
  "Dashboard style": "Style du tableau de bord",
  "Sidebar style": "Style de la barre latérale",
  Density: "Densité",
  "Corner style": "Style des coins",
  Timezone: "Fuseau horaire",
  "Date format": "Format de date",
  "Invoice prefix": "Préfixe de facture",
  "Tax label": "Libellé de taxe",
  "Default tax rate": "Taux de taxe par défaut",
  "Show setup checklist": "Afficher la liste de configuration",
  "Show finance pulse": "Afficher l'aperçu financier",
  "Email reminders": "Rappels par e-mail",
  "Payment terms": "Conditions de paiement",
  "Reminder tone": "Ton des rappels",
  "Choose your plan": "Choisissez votre forfait",
  "Step 1 of 2": "Étape 1 sur 2",
  "Choose plan": "Choisir le forfait",
  "Plan selected": "Forfait sélectionné",
  "Plan summary": "Résumé du forfait",
  "Due today": "Dû aujourd'hui",
  "Due on payment page": "Dû sur la page de paiement",
  "Open dashboard": "Ouvrir le tableau de bord",
  "Start 3-day trial": "Démarrer l'essai de 3 jours",
  "Continue to payment": "Continuer vers le paiement",
  "Business intelligence": "Analyse d'activité",
  "Executive snapshot": "Vue exécutive",
  "Current profit / loss": "Profit / perte actuel",
  "Recorded income": "Revenus enregistrés",
  "Profit / loss": "Profit / perte",
  "Cash flow": "Flux de trésorerie",
  "Invoice total": "Total des factures",
  "Unpaid invoices": "Factures impayées",
  "Supplier bills": "Factures fournisseurs",
  "Tax tracked": "Taxe suivie",
  "Collection rate": "Taux de recouvrement",
  "Operating load": "Charge opérationnelle",
  Contact: "Contact",
  Support: "Assistance",
  Billing: "Facturation",
  Privacy: "Confidentialité",
  "Send a request": "Envoyer une demande",
  "Tell us what you need": "Dites-nous ce dont vous avez besoin",
  Topic: "Sujet",
  Message: "Message",
  "Save request": "Enregistrer la demande",
  "Response time": "Délai de réponse",
  "Employee ID": "ID employé",
  "ID card number": "Numéro de pièce d'identité",
  "ID card expiry": "Expiration de la pièce d'identité",
  "Emergency contact name": "Contact d'urgence",
  "Emergency contact phone": "Téléphone du contact d'urgence",
});

Object.assign(common.Spanish, {
  "Comvexa gives companies one workspace for customers, employees, bookings, tasks, invoices, payments, expenses, documents, reports, branches, inventory, and daily operations.": "Comvexa ofrece a las empresas un único espacio de trabajo para gestionar clientes, empleados, reservas, tareas, facturas, pagos, gastos, documentos, informes, sucursales, inventario y operaciones diarias.",
  "Global company management software": "Software global de gestión empresarial",
  "Everything your company needs to operate.": "Todo lo que tu empresa necesita para operar.",
  "Finance and accounting": "Finanzas y contabilidad",
  "Know where the money is going.": "Ten claridad sobre el movimiento del dinero.",
  Workflow: "Flujo de trabajo",
  "From first customer to final report.": "Del primer cliente al informe final.",
  "Plans that match your operating stage.": "Planes para cada etapa operativa.",
  "Security and global readiness": "Seguridad y preparación global",
  "Built for multi-company SaaS from the start.": "Diseñado desde el inicio para SaaS multiempresa.",
  "Questions before you start?": "¿Preguntas antes de empezar?",
  "Ready to start": "Listo para comenzar",
  Account: "Cuenta",
  Legal: "Legal",
  "Contact Us": "Contáctanos",
  "Privacy Policy": "Política de privacidad",
  "Terms of Service": "Términos del servicio",
  "Refund Policy": "Política de reembolso",
  "Cookie Policy": "Política de cookies",
  "No free trial": "Sin prueba gratuita",
  "3-day free trial": "Prueba gratuita de 3 días",
  "Yearly billing includes 2 months free.": "La facturación anual incluye 2 meses gratis.",
  "Switch to yearly to see annual pricing.": "Cambia a anual para ver el precio anual.",
  "Global-ready": "Preparado para operar globalmente",
  "Operations-first": "Pensado para operaciones",
  "Plan controlled": "Controlado por plan",
  "Try Pro for 3 days before continuing monthly.": "Prueba Pro durante 3 días antes de continuar mensualmente.",
  "Services & Products": "Servicios y productos",
  "Staff Schedules": "Horarios del personal",
  "Recurring Invoices": "Facturas recurrentes",
  "Supplier Bills": "Facturas de proveedores",
  "WhatsApp Templates": "Plantillas de WhatsApp",
  "Company Identity": "Identidad de la empresa",
  Appearance: "Apariencia",
  "Regional and Accounting Defaults": "Valores regionales y contables",
  "Workflow Controls": "Controles de flujo",
  "Module Visibility": "Visibilidad de módulos",
  "Display name": "Nombre visible",
  Industry: "Sector",
  "Default start page": "Página inicial predeterminada",
  "Display language": "Idioma de visualización",
  "Accent color": "Color principal",
  "Dashboard style": "Estilo del panel",
  "Sidebar style": "Estilo de la barra lateral",
  Density: "Densidad",
  "Corner style": "Estilo de esquinas",
  Timezone: "Zona horaria",
  "Date format": "Formato de fecha",
  "Invoice prefix": "Prefijo de factura",
  "Tax label": "Etiqueta de impuesto",
  "Default tax rate": "Tasa de impuesto predeterminada",
  "Show setup checklist": "Mostrar lista de configuración",
  "Show finance pulse": "Mostrar resumen financiero",
  "Email reminders": "Recordatorios por correo",
  "Payment terms": "Condiciones de pago",
  "Reminder tone": "Tono del recordatorio",
  "Choose your plan": "Elige tu plan",
  "Step 1 of 2": "Paso 1 de 2",
  "Choose plan": "Elegir plan",
  "Plan selected": "Plan seleccionado",
  "Plan summary": "Resumen del plan",
  "Due today": "Vence hoy",
  "Due on payment page": "Vence en la página de pago",
  "Open dashboard": "Abrir panel",
  "Start 3-day trial": "Iniciar prueba de 3 días",
  "Continue to payment": "Continuar al pago",
  "Business intelligence": "Inteligencia empresarial",
  "Executive snapshot": "Resumen ejecutivo",
  "Current profit / loss": "Ganancia / pérdida actual",
  "Recorded income": "Ingresos registrados",
  "Profit / loss": "Ganancia / pérdida",
  "Cash flow": "Flujo de caja",
  "Invoice total": "Total facturado",
  "Unpaid invoices": "Facturas pendientes",
  "Supplier bills": "Facturas de proveedores",
  "Tax tracked": "Impuesto registrado",
  "Collection rate": "Tasa de cobro",
  "Operating load": "Carga operativa",
  Contact: "Contacto",
  Support: "Soporte",
  Billing: "Facturación",
  Privacy: "Privacidad",
  "Send a request": "Enviar solicitud",
  "Tell us what you need": "Cuéntanos qué necesitas",
  Topic: "Tema",
  Message: "Mensaje",
  "Save request": "Guardar solicitud",
  "Response time": "Tiempo de respuesta",
  "Employee ID": "ID de empleado",
  "ID card number": "Número de documento",
  "ID card expiry": "Vencimiento del documento",
  "Emergency contact name": "Contacto de emergencia",
  "Emergency contact phone": "Teléfono de emergencia",
});

Object.assign(common.Arabic, {
  "Profiles, notes, balances, history, and contact details.": "ملفات العملاء والملاحظات والأرصدة والسجل وبيانات التواصل.",
  "Staff records, roles, salaries, schedules, and accountability.": "سجلات الموظفين والأدوار والرواتب والجداول والمسؤوليات.",
  "Appointments, field work, service times, and operational planning.": "المواعيد والعمل الميداني وأوقات الخدمة والتخطيط التشغيلي.",
  "Priorities, due dates, owners, and everyday team follow-up.": "الأولويات وتواريخ الاستحقاق والمسؤولون والمتابعة اليومية للفريق.",
  "Invoice records, totals, due dates, payment status, and items.": "سجلات الفواتير والإجماليات وتواريخ الاستحقاق وحالة الدفع والبنود.",
  "Payment methods, payment dates, notes, and collection tracking.": "طرق الدفع وتواريخ الدفع والملاحظات وتتبع التحصيل.",
  "Categories, vendors, tax amounts, and business cost tracking.": "الفئات والموردون ومبالغ الضريبة وتتبع تكاليف العمل.",
  "PDF uploads, expiry dates, file types, and secure company storage.": "رفع ملفات PDF وتواريخ الانتهاء وأنواع الملفات وتخزين آمن للشركة.",
  "Stock quantities, suppliers, units, and low-stock alerts.": "كميات المخزون والموردون والوحدات وتنبيهات انخفاض المخزون.",
  "Revenue, expenses, cash flow, profit/loss, and operations summaries.": "الإيرادات والمصروفات والتدفق النقدي والربح والخسارة وملخصات العمليات.",
  "Locations, contact numbers, and branch-level organization.": "المواقع وأرقام التواصل وتنظيم الفروع.",
  "Prepare module access rules for staff, managers, and admins.": "إعداد قواعد الوصول للوحدات للموظفين والمديرين والمشرفين.",
  "Service companies": "شركات الخدمات",
  "Retail stores": "متاجر التجزئة",
  Agencies: "الوكالات",
  Clinics: "العيادات",
  Contractors: "المقاولون",
  Salons: "الصالونات",
  "Maintenance teams": "فرق الصيانة",
  "Field operations": "العمليات الميدانية",
});

Object.assign(common.German, {
  "Everything your company needs to operate.": "Alles, was Ihr Unternehmen für den Betrieb benötigt.",
  "Comvexa is not a single-purpose tool. It combines operations, finance, documents, people, inventory, reports, and company settings in one organized workspace.": "Comvexa ist kein Einzweck-Tool. Es bündelt Betrieb, Finanzen, Dokumente, Mitarbeitende, Inventar, Berichte und Unternehmenseinstellungen in einem organisierten Arbeitsbereich.",
  "Profiles, notes, balances, history, and contact details.": "Profile, Notizen, Salden, Verlauf und Kontaktdaten.",
  "Staff records, roles, salaries, schedules, and accountability.": "Mitarbeiterdaten, Rollen, Gehälter, Dienstpläne und Verantwortlichkeiten.",
  "Appointments, field work, service times, and operational planning.": "Termine, Außendienst, Servicezeiten und operative Planung.",
  "Priorities, due dates, owners, and everyday team follow-up.": "Prioritäten, Fälligkeiten, Verantwortliche und tägliche Nachverfolgung.",
  "Invoice records, totals, due dates, payment status, and items.": "Rechnungsdaten, Summen, Fälligkeiten, Zahlungsstatus und Positionen.",
  "Payment methods, payment dates, notes, and collection tracking.": "Zahlungsarten, Zahlungsdaten, Notizen und Inkassoverfolgung.",
  "Categories, vendors, tax amounts, and business cost tracking.": "Kategorien, Anbieter, Steuerbeträge und Kostenverfolgung.",
  "PDF uploads, expiry dates, file types, and secure company storage.": "PDF-Uploads, Ablaufdaten, Dateitypen und sichere Unternehmensablage.",
  "Stock quantities, suppliers, units, and low-stock alerts.": "Bestände, Lieferanten, Einheiten und Warnungen bei niedrigem Lagerbestand.",
  "Revenue, expenses, cash flow, profit/loss, and operations summaries.": "Umsatz, Ausgaben, Cashflow, Gewinn und Verlust sowie Betriebsübersichten.",
  "Locations, contact numbers, and branch-level organization.": "Standorte, Kontaktnummern und Organisation auf Filialebene.",
  "Prepare module access rules for staff, managers, and admins.": "Zugriffsregeln für Mitarbeitende, Manager und Administratoren vorbereiten.",
  "Service companies": "Dienstleistungsunternehmen",
  "Retail stores": "Einzelhandel",
  Agencies: "Agenturen",
  Clinics: "Kliniken",
  Contractors: "Auftragnehmer",
  Salons: "Salons",
  "Maintenance teams": "Wartungsteams",
  "Field operations": "Außendienst",
});

Object.assign(common.French, {
  "Everything your company needs to operate.": "Tout ce dont votre entreprise a besoin pour fonctionner.",
  "Comvexa is not a single-purpose tool. It combines operations, finance, documents, people, inventory, reports, and company settings in one organized workspace.": "Comvexa n'est pas un outil à usage unique. Il réunit opérations, finance, documents, équipes, inventaire, rapports et paramètres d'entreprise dans un espace de travail organisé.",
  "Profiles, notes, balances, history, and contact details.": "Profils, notes, soldes, historique et coordonnées.",
  "Staff records, roles, salaries, schedules, and accountability.": "Dossiers du personnel, rôles, salaires, plannings et responsabilités.",
  "Appointments, field work, service times, and operational planning.": "Rendez-vous, travail terrain, temps de service et planification opérationnelle.",
  "Priorities, due dates, owners, and everyday team follow-up.": "Priorités, échéances, responsables et suivi quotidien de l'équipe.",
  "Invoice records, totals, due dates, payment status, and items.": "Factures, totaux, échéances, statuts de paiement et lignes.",
  "Payment methods, payment dates, notes, and collection tracking.": "Modes de paiement, dates, notes et suivi des encaissements.",
  "Categories, vendors, tax amounts, and business cost tracking.": "Catégories, fournisseurs, taxes et suivi des coûts.",
  "PDF uploads, expiry dates, file types, and secure company storage.": "Téléversements PDF, dates d'expiration, types de fichiers et stockage sécurisé.",
  "Stock quantities, suppliers, units, and low-stock alerts.": "Stocks, fournisseurs, unités et alertes de stock faible.",
  "Revenue, expenses, cash flow, profit/loss, and operations summaries.": "Revenus, dépenses, trésorerie, profit et perte, et synthèses opérationnelles.",
  "Locations, contact numbers, and branch-level organization.": "Sites, numéros de contact et organisation par succursale.",
  "Prepare module access rules for staff, managers, and admins.": "Préparer les règles d'accès aux modules pour employés, managers et administrateurs.",
  "Service companies": "Entreprises de services",
  "Retail stores": "Commerces de détail",
  Agencies: "Agences",
  Clinics: "Cliniques",
  Contractors: "Entrepreneurs",
  Salons: "Salons",
  "Maintenance teams": "Équipes de maintenance",
  "Field operations": "Opérations terrain",
});

Object.assign(common.Spanish, {
  "Everything your company needs to operate.": "Todo lo que tu empresa necesita para operar.",
  "Comvexa is not a single-purpose tool. It combines operations, finance, documents, people, inventory, reports, and company settings in one organized workspace.": "Comvexa no es una herramienta de un solo propósito. Reúne operaciones, finanzas, documentos, personas, inventario, informes y configuración de empresa en un espacio organizado.",
  "Profiles, notes, balances, history, and contact details.": "Perfiles, notas, saldos, historial y datos de contacto.",
  "Staff records, roles, salaries, schedules, and accountability.": "Registros del personal, roles, salarios, horarios y responsabilidades.",
  "Appointments, field work, service times, and operational planning.": "Citas, trabajo de campo, tiempos de servicio y planificación operativa.",
  "Priorities, due dates, owners, and everyday team follow-up.": "Prioridades, vencimientos, responsables y seguimiento diario.",
  "Invoice records, totals, due dates, payment status, and items.": "Registros de facturas, totales, vencimientos, estado de pago y conceptos.",
  "Payment methods, payment dates, notes, and collection tracking.": "Métodos de pago, fechas, notas y seguimiento de cobros.",
  "Categories, vendors, tax amounts, and business cost tracking.": "Categorías, proveedores, impuestos y seguimiento de costes.",
  "PDF uploads, expiry dates, file types, and secure company storage.": "Carga de PDF, fechas de vencimiento, tipos de archivo y almacenamiento seguro.",
  "Stock quantities, suppliers, units, and low-stock alerts.": "Cantidades de stock, proveedores, unidades y alertas de bajo inventario.",
  "Revenue, expenses, cash flow, profit/loss, and operations summaries.": "Ingresos, gastos, flujo de caja, ganancia y pérdida, y resúmenes operativos.",
  "Locations, contact numbers, and branch-level organization.": "Ubicaciones, teléfonos y organización por sucursal.",
  "Prepare module access rules for staff, managers, and admins.": "Preparar reglas de acceso para personal, gerentes y administradores.",
  "Service companies": "Empresas de servicios",
  "Retail stores": "Tiendas minoristas",
  Agencies: "Agencias",
  Clinics: "Clínicas",
  Contractors: "Contratistas",
  Salons: "Salones",
  "Maintenance teams": "Equipos de mantenimiento",
  "Field operations": "Operaciones de campo",
});

Object.assign(common.Arabic, {
  "Comvexa Command Center": "مركز قيادة Comvexa",
  "Live business overview": "نظرة مباشرة على الأعمال",
  Connected: "متصل",
  Revenue: "الإيرادات",
  "Payment received": "تم استلام دفعة",
  "PDF contract uploaded": "تم رفع عقد PDF",
  "Staff schedule updated": "تم تحديث جدول الموظفين",
  "Supplier bill created": "تم إنشاء فاتورة مورد",
  "Accounting snapshot": "لمحة محاسبية",
  Income: "الدخل",
  Profit: "الربح",
  "Operations workspace": "مساحة العمليات",
  "Accounting tools": "أدوات المحاسبة",
  "Subscription plans": "خطط الاشتراك",
  Questions: "الأسئلة",
  "Business Modules": "وحدات الأعمال",
  "Customers and employees": "العملاء والموظفون",
  "Bookings and tasks": "الحجوزات والمهام",
  "Invoices and payments": "الفواتير والمدفوعات",
  "Documents and reports": "المستندات والتقارير",
  Finance: "المالية",
  "Expenses and supplier bills": "المصروفات وفواتير الموردين",
  "Cash flow overview": "نظرة على التدفق النقدي",
  "Profit and loss summary": "ملخص الربح والخسارة",
  "Tax tracking fields": "حقول تتبع الضريبة",
  "Secure account access": "وصول آمن للحساب",
  "Global SaaS": "منصة SaaS عالمية",
  "Multi-company": "متعددة الشركات",
  "Plan-based access": "وصول حسب الخطة",
  "Copyright 2026 Comvexa. All rights reserved.": "حقوق النشر 2026 Comvexa. جميع الحقوق محفوظة.",
  "Welcome back": "مرحباً بعودتك",
  "Create account": "إنشاء حساب",
  "Workspace setup": "إعداد مساحة العمل",
  "Quick actions": "إجراءات سريعة",
  "Recorded revenue": "الإيرادات المسجلة",
  "Next best step": "أفضل خطوة تالية",
  "Uploaded PDFs": "ملفات PDF المرفوعة",
  "Document type": "نوع المستند",
  "Expiry date": "تاريخ الانتهاء",
  "PDF file": "ملف PDF",
  "Payment setup": "إعداد الدفع",
  "Payment method": "طريقة الدفع",
  "Choose how this company will pay.": "اختر كيف ستدفع هذه الشركة.",
  "Order summary": "ملخص الطلب",
  Plan: "الخطة",
  Billing: "الفوترة",
  "Free trial": "تجربة مجانية",
  "Due now": "المستحق الآن",
  "Sample data for the current company workspace.": "بيانات نموذجية لمساحة عمل الشركة الحالية.",
  "Create and track customer invoices": "إنشاء وتتبع فواتير العملاء",
  "Record collection method and dates": "تسجيل طريقة التحصيل وتواريخه",
  "Track categories, vendors, and tax": "تتبع الفئات والموردين والضرائب",
  "Monitor payables and due dates": "متابعة المستحقات وتواريخ الاستحقاق",
  "Comvexa helps businesses manage the financial side of operations: invoices, payments, expenses, supplier bills, taxes, receivables, cash flow, and profit/loss summaries.": "تساعد Comvexa الشركات على إدارة الجانب المالي من العمليات: الفواتير والمدفوعات والمصروفات وفواتير الموردين والضرائب والذمم المدينة والتدفق النقدي وملخصات الربح والخسارة.",
  "Accounts receivable and unpaid invoice follow-up": "متابعة الذمم المدينة والفواتير غير المدفوعة",
  "Expense categories, tax amounts, vendors, and notes": "فئات المصروفات ومبالغ الضرائب والموردون والملاحظات",
  "Cash flow, profit/loss, income, and supplier bill reports": "تقارير التدفق النقدي والربح والخسارة والدخل وفواتير الموردين",
  "Accountant-ready exports planned for Ultra workflows": "تصديرات جاهزة للمحاسب مخططة لسير عمل Ultra",
});

Object.assign(common.German, {
  "Comvexa Command Center": "Comvexa-Kommandozentrale",
  "Live business overview": "Live-Geschäftsübersicht",
  Connected: "Verbunden",
  Revenue: "Umsatz",
  "Payment received": "Zahlung erhalten",
  "PDF contract uploaded": "PDF-Vertrag hochgeladen",
  "Staff schedule updated": "Dienstplan aktualisiert",
  "Supplier bill created": "Lieferantenrechnung erstellt",
  "Accounting snapshot": "Buchhaltungsübersicht",
  Income: "Einnahmen",
  Profit: "Gewinn",
  "Operations workspace": "Betriebsarbeitsbereich",
  "Accounting tools": "Buchhaltungstools",
  "Subscription plans": "Abonnement-Tarife",
  Questions: "Fragen",
  "Business Modules": "Geschäftsmodule",
  "Customers and employees": "Kunden und Mitarbeitende",
  "Bookings and tasks": "Buchungen und Aufgaben",
  "Invoices and payments": "Rechnungen und Zahlungen",
  "Documents and reports": "Dokumente und Berichte",
  Finance: "Finanzen",
  "Expenses and supplier bills": "Ausgaben und Lieferantenrechnungen",
  "Cash flow overview": "Cashflow-Übersicht",
  "Profit and loss summary": "Gewinn- und Verlustübersicht",
  "Tax tracking fields": "Felder zur Steuerverfolgung",
  "Secure account access": "Sicherer Kontozugriff",
  "Global SaaS": "Globales SaaS",
  "Multi-company": "Mehrere Unternehmen",
  "Plan-based access": "Tarifbasierter Zugriff",
  "Copyright 2026 Comvexa. All rights reserved.": "Copyright 2026 Comvexa. Alle Rechte vorbehalten.",
  "Welcome back": "Willkommen zurück",
  "Create account": "Konto erstellen",
  "Workspace setup": "Arbeitsbereich einrichten",
  "Quick actions": "Schnellaktionen",
  "Recorded revenue": "Erfasster Umsatz",
  "Next best step": "Nächster sinnvoller Schritt",
  "Uploaded PDFs": "Hochgeladene PDFs",
  "Document type": "Dokumenttyp",
  "Expiry date": "Ablaufdatum",
  "PDF file": "PDF-Datei",
  "Payment setup": "Zahlung einrichten",
  "Payment method": "Zahlungsmethode",
  "Choose how this company will pay.": "Wählen Sie aus, wie dieses Unternehmen bezahlt.",
  "Order summary": "Bestellübersicht",
  Plan: "Tarif",
  Billing: "Abrechnung",
  "Free trial": "Kostenlose Testphase",
  "Due now": "Jetzt fällig",
  "Sample data for the current company workspace.": "Beispieldaten für den aktuellen Unternehmensarbeitsbereich.",
  "Create and track customer invoices": "Kundenrechnungen erstellen und verfolgen",
  "Record collection method and dates": "Inkassomethode und Zahlungstermine erfassen",
  "Track categories, vendors, and tax": "Kategorien, Anbieter und Steuern verfolgen",
  "Monitor payables and due dates": "Verbindlichkeiten und Fälligkeiten überwachen",
  "Comvexa helps businesses manage the financial side of operations: invoices, payments, expenses, supplier bills, taxes, receivables, cash flow, and profit/loss summaries.": "Comvexa hilft Unternehmen, die finanzielle Seite des Betriebs zu verwalten: Rechnungen, Zahlungen, Ausgaben, Lieferantenrechnungen, Steuern, Forderungen, Cashflow sowie Gewinn- und Verlustübersichten.",
  "Accounts receivable and unpaid invoice follow-up": "Forderungen und Nachverfolgung offener Rechnungen",
  "Expense categories, tax amounts, vendors, and notes": "Ausgabenkategorien, Steuerbeträge, Anbieter und Notizen",
  "Cash flow, profit/loss, income, and supplier bill reports": "Berichte zu Cashflow, Gewinn und Verlust, Einnahmen und Lieferantenrechnungen",
  "Accountant-ready exports planned for Ultra workflows": "Buchhalterfertige Exporte für Ultra-Workflows geplant",
});

Object.assign(common.French, {
  "Comvexa Command Center": "Centre de commande Comvexa",
  "Live business overview": "Vue d'activité en direct",
  Connected: "Connecté",
  Revenue: "Revenus",
  "Payment received": "Paiement reçu",
  "PDF contract uploaded": "Contrat PDF téléversé",
  "Staff schedule updated": "Planning du personnel mis à jour",
  "Supplier bill created": "Facture fournisseur créée",
  "Accounting snapshot": "Aperçu comptable",
  Income: "Revenus",
  Profit: "Profit",
  "Operations workspace": "Espace opérations",
  "Accounting tools": "Outils comptables",
  "Subscription plans": "Forfaits",
  Questions: "Questions",
  "Business Modules": "Modules métier",
  "Customers and employees": "Clients et employés",
  "Bookings and tasks": "Réservations et tâches",
  "Invoices and payments": "Factures et paiements",
  "Documents and reports": "Documents et rapports",
  Finance: "Finance",
  "Expenses and supplier bills": "Dépenses et factures fournisseurs",
  "Cash flow overview": "Vue de trésorerie",
  "Profit and loss summary": "Résumé profit et perte",
  "Tax tracking fields": "Champs de suivi fiscal",
  "Secure account access": "Accès sécurisé au compte",
  "Global SaaS": "SaaS mondial",
  "Multi-company": "Multi-entreprise",
  "Plan-based access": "Accès selon le forfait",
  "Copyright 2026 Comvexa. All rights reserved.": "Copyright 2026 Comvexa. Tous droits réservés.",
  "Welcome back": "Bon retour",
  "Create account": "Créer un compte",
  "Workspace setup": "Configuration de l'espace",
  "Quick actions": "Actions rapides",
  "Recorded revenue": "Revenus enregistrés",
  "Next best step": "Prochaine étape recommandée",
  "Uploaded PDFs": "PDF téléversés",
  "Document type": "Type de document",
  "Expiry date": "Date d'expiration",
  "PDF file": "Fichier PDF",
  "Payment setup": "Configuration du paiement",
  "Payment method": "Mode de paiement",
  "Choose how this company will pay.": "Choisissez comment cette entreprise paiera.",
  "Order summary": "Résumé de commande",
  Plan: "Forfait",
  Billing: "Facturation",
  "Free trial": "Essai gratuit",
  "Due now": "Dû maintenant",
  "Sample data for the current company workspace.": "Données d'exemple pour l'espace de travail actuel.",
  "Create and track customer invoices": "Créer et suivre les factures clients",
  "Record collection method and dates": "Enregistrer les modes et dates d'encaissement",
  "Track categories, vendors, and tax": "Suivre les catégories, fournisseurs et taxes",
  "Monitor payables and due dates": "Suivre les dettes fournisseurs et échéances",
  "Comvexa helps businesses manage the financial side of operations: invoices, payments, expenses, supplier bills, taxes, receivables, cash flow, and profit/loss summaries.": "Comvexa aide les entreprises à gérer la partie financière des opérations : factures, paiements, dépenses, factures fournisseurs, taxes, créances, trésorerie et synthèses de profit et perte.",
  "Accounts receivable and unpaid invoice follow-up": "Suivi des créances clients et des factures impayées",
  "Expense categories, tax amounts, vendors, and notes": "Catégories de dépenses, montants de taxe, fournisseurs et notes",
  "Cash flow, profit/loss, income, and supplier bill reports": "Rapports de trésorerie, profit et perte, revenus et factures fournisseurs",
  "Accountant-ready exports planned for Ultra workflows": "Exports prêts pour comptable prévus pour les workflows Ultra",
});

Object.assign(common.Spanish, {
  "Comvexa Command Center": "Centro de comando Comvexa",
  "Live business overview": "Resumen del negocio en vivo",
  Connected: "Conectado",
  Revenue: "Ingresos",
  "Payment received": "Pago recibido",
  "PDF contract uploaded": "Contrato PDF cargado",
  "Staff schedule updated": "Horario del personal actualizado",
  "Supplier bill created": "Factura de proveedor creada",
  "Accounting snapshot": "Resumen contable",
  Income: "Ingresos",
  Profit: "Ganancia",
  "Operations workspace": "Espacio de operaciones",
  "Accounting tools": "Herramientas contables",
  "Subscription plans": "Planes de suscripción",
  Questions: "Preguntas",
  "Business Modules": "Módulos de negocio",
  "Customers and employees": "Clientes y empleados",
  "Bookings and tasks": "Reservas y tareas",
  "Invoices and payments": "Facturas y pagos",
  "Documents and reports": "Documentos e informes",
  Finance: "Finanzas",
  "Expenses and supplier bills": "Gastos y facturas de proveedores",
  "Cash flow overview": "Resumen de flujo de caja",
  "Profit and loss summary": "Resumen de ganancias y pérdidas",
  "Tax tracking fields": "Campos de seguimiento fiscal",
  "Secure account access": "Acceso seguro a la cuenta",
  "Global SaaS": "SaaS global",
  "Multi-company": "Multiempresa",
  "Plan-based access": "Acceso según el plan",
  "Copyright 2026 Comvexa. All rights reserved.": "Copyright 2026 Comvexa. Todos los derechos reservados.",
  "Welcome back": "Bienvenido de nuevo",
  "Create account": "Crear cuenta",
  "Workspace setup": "Configuración del espacio",
  "Quick actions": "Acciones rápidas",
  "Recorded revenue": "Ingresos registrados",
  "Next best step": "Siguiente mejor paso",
  "Uploaded PDFs": "PDF cargados",
  "Document type": "Tipo de documento",
  "Expiry date": "Fecha de vencimiento",
  "PDF file": "Archivo PDF",
  "Payment setup": "Configuración de pago",
  "Payment method": "Método de pago",
  "Choose how this company will pay.": "Elige cómo pagará esta empresa.",
  "Order summary": "Resumen del pedido",
  Plan: "Plan",
  Billing: "Facturación",
  "Free trial": "Prueba gratuita",
  "Due now": "Vence ahora",
  "Sample data for the current company workspace.": "Datos de ejemplo para el espacio de trabajo actual.",
  "Create and track customer invoices": "Crear y controlar facturas de clientes",
  "Record collection method and dates": "Registrar método y fechas de cobro",
  "Track categories, vendors, and tax": "Controlar categorías, proveedores e impuestos",
  "Monitor payables and due dates": "Supervisar cuentas por pagar y vencimientos",
  "Comvexa helps businesses manage the financial side of operations: invoices, payments, expenses, supplier bills, taxes, receivables, cash flow, and profit/loss summaries.": "Comvexa ayuda a las empresas a gestionar la parte financiera de sus operaciones: facturas, pagos, gastos, facturas de proveedores, impuestos, cuentas por cobrar, flujo de caja y resúmenes de ganancias y pérdidas.",
  "Accounts receivable and unpaid invoice follow-up": "Seguimiento de cuentas por cobrar y facturas pendientes",
  "Expense categories, tax amounts, vendors, and notes": "Categorías de gastos, importes de impuestos, proveedores y notas",
  "Cash flow, profit/loss, income, and supplier bill reports": "Informes de flujo de caja, ganancias y pérdidas, ingresos y facturas de proveedores",
  "Accountant-ready exports planned for Ultra workflows": "Exportaciones listas para contabilidad previstas para flujos Ultra",
});

Object.assign(common.German, {
  "business modules": "Geschäftsmodule",
  "subscription plans": "Abonnement-Tarife",
  "Pro free trial": "Kostenlose Pro-Testphase",
  "Global-ready": "Weltweit einsatzbereit",
  "Works for teams, branches, and markets worldwide.": "Geeignet für Teams, Filialen und Märkte weltweit.",
  "Operations-first": "Für den Betrieb gemacht",
  "Customers, staff, work, invoices, and reports together.": "Kunden, Mitarbeitende, Arbeit, Rechnungen und Berichte an einem Ort.",
  "Plan controlled": "Tarifgesteuert",
  "Only unlock the modules included in each subscription.": "Nur die Module freischalten, die im jeweiligen Abonnement enthalten sind.",
  "Pro trial": "Pro-Testphase",
  "Try Pro for 3 days before continuing monthly.": "Testen Sie Pro 3 Tage lang, bevor Sie monatlich fortfahren.",
  Basic: "Basis",
  "Essential tools for small businesses and freelancers.": "Wichtige Werkzeuge für kleine Unternehmen und Freiberufler.",
  "The best starting point for growing companies with staff.": "Der beste Einstieg für wachsende Unternehmen mit Mitarbeitenden.",
  "Full control for companies with branches, stock, and permissions.": "Volle Kontrolle für Unternehmen mit Filialen, Lagerbestand und Berechtigungen.",
  "Customer management": "Kundenverwaltung",
  "Services/products": "Dienstleistungen/Produkte",
  "Customer balances": "Kundensalden",
  "Basic reports": "Basisberichte",
  "Company settings": "Unternehmenseinstellungen",
  "Everything in Basic": "Alles aus Basis",
  "Employee management": "Mitarbeiterverwaltung",
  "Staff schedules": "Dienstpläne",
  "Documents and PDF uploads": "Dokumente und PDF-Uploads",
  "Recurring invoices": "Wiederkehrende Rechnungen",
  "Payment reminders": "Zahlungserinnerungen",
  "WhatsApp templates": "WhatsApp-Vorlagen",
  "Profit and loss summary": "Gewinn- und Verlustübersicht",
  "Advanced reports": "Erweiterte Berichte",
  "Everything in Pro": "Alles aus Pro",
  "Multiple branches": "Mehrere Filialen",
  "Inventory management": "Inventarverwaltung",
  "Supplier bills": "Lieferantenrechnungen",
  "Advanced permissions": "Erweiterte Berechtigungen",
  "Payment reconciliation": "Zahlungsabgleich",
  "Multi-currency records": "Datensätze in mehreren Währungen",
  "Custom tax settings": "Individuelle Steuereinstellungen",
  "Priority support": "Priorisierter Support",
  "Can Comvexa work for any industry?": "Kann Comvexa für jede Branche genutzt werden?",
  "Is company data separated?": "Sind Unternehmensdaten getrennt?",
  "Does Comvexa include accounting tools?": "Enthält Comvexa Buchhaltungswerkzeuge?",
  "Which plan has a free trial?": "Welcher Tarif hat eine kostenlose Testphase?",
  "Yes. Comvexa is designed as a flexible company management platform for service businesses, retailers, agencies, clinics, contractors, and many other operating teams.": "Ja. Comvexa ist als flexible Unternehmensplattform für Dienstleister, Einzelhandel, Agenturen, Kliniken, Auftragnehmer und viele andere operative Teams konzipiert.",
  "Yes. Company records are separated by workspace so each business can only access its own data when security rules are applied.": "Ja. Unternehmensdaten werden nach Arbeitsbereich getrennt, damit jedes Unternehmen bei aktivierten Sicherheitsregeln nur auf seine eigenen Daten zugreifen kann.",
  "Comvexa includes invoices, payments, expenses, supplier bills, tax tracking fields, receivables, cash flow, and profit/loss summaries. It is built for operational accounting workflows.": "Comvexa umfasst Rechnungen, Zahlungen, Ausgaben, Lieferantenrechnungen, Steuerfelder, Forderungen, Cashflow sowie Gewinn- und Verlustübersichten. Es ist für operative Buchhaltungsabläufe gebaut.",
  "Only Pro includes a free trial, and the trial lasts 3 days. Basic and Ultra do not include a free trial.": "Nur Pro enthält eine kostenlose Testphase von 3 Tagen. Basis und Ultra enthalten keine kostenlose Testphase.",
  "Create company workspace": "Unternehmensarbeitsbereich erstellen",
  "Register, choose a plan, complete payment setup.": "Registrieren, Tarif wählen und Zahlungseinrichtung abschließen.",
  "Add business data": "Geschäftsdaten hinzufügen",
  "Customers, employees, services, invoices, tasks, and documents.": "Kunden, Mitarbeitende, Dienstleistungen, Rechnungen, Aufgaben und Dokumente.",
  "Run daily operations": "Tägliche Abläufe steuern",
  "Assign work, schedule bookings, record payments, upload PDFs.": "Arbeit zuweisen, Buchungen planen, Zahlungen erfassen und PDFs hochladen.",
  "Review performance": "Leistung auswerten",
  "Use reports for income, expenses, cash flow, tasks, and bookings.": "Berichte für Einnahmen, Ausgaben, Cashflow, Aufgaben und Buchungen nutzen.",
  "Users sign up first, choose a plan, then continue to payment. Only Pro includes a 3-day free trial.": "Benutzer registrieren sich zuerst, wählen einen Tarif und fahren dann mit der Zahlung fort. Nur Pro enthält eine kostenlose 3-Tage-Testphase.",
  "Every operational table is designed around company isolation. The platform is prepared for global settings, PDF storage, plan-based access, permissions, and future payment automation.": "Jede operative Tabelle ist auf Unternehmensisolierung ausgelegt. Die Plattform ist für globale Einstellungen, PDF-Speicher, tarifbasierten Zugriff, Berechtigungen und zukünftige Zahlungsautomatisierung vorbereitet.",
  "Company-isolated data": "Unternehmensgetrennte Daten",
  "Business records are tied to company_id.": "Geschäftsdatensätze sind mit company_id verknüpft.",
  "Global settings": "Globale Einstellungen",
  "Currency, timezone, and workspace customization.": "Währung, Zeitzone und Anpassung des Arbeitsbereichs.",
  "Plan-based modules": "Tarifbasierte Module",
  "Users only see modules included in their plan.": "Benutzer sehen nur Module, die in ihrem Tarif enthalten sind.",
  "Secure documents": "Sichere Dokumente",
  "PDFs can be stored in private company file storage.": "PDFs können in privatem Unternehmensspeicher abgelegt werden.",
  "Start with your company workspace": "Starten Sie mit Ihrem Unternehmensarbeitsbereich",
  "Sign up, choose your plan, complete payment setup, then open your dashboard.": "Registrieren Sie sich, wählen Sie Ihren Tarif, schließen Sie die Zahlungseinrichtung ab und öffnen Sie dann Ihr Dashboard.",
  "Comvexa is built step by step so your company can start simple, then expand into accounting, operations, documents, inventory, permissions, and reports.": "Comvexa ist schrittweise aufgebaut, damit Ihr Unternehmen einfach starten und später Buchhaltung, Betrieb, Dokumente, Inventar, Berechtigungen und Berichte erweitern kann.",
  "Run customers, staff, bookings, invoices, payments, expenses, documents, inventory, branches, permissions, and reports from one professional workspace built for global businesses.": "Verwalten Sie Kunden, Mitarbeitende, Buchungen, Rechnungen, Zahlungen, Ausgaben, Dokumente, Inventar, Filialen, Berechtigungen und Berichte in einem professionellen Arbeitsbereich für globale Unternehmen.",
  "Company data": "Unternehmensdaten",
  "Separated by workspace": "Nach Arbeitsbereich getrennt",
  "3 days included": "3 Tage enthalten",
  Plans: "Tarife",
  "Basic, Pro, Ultra": "Basis, Pro, Ultra",
  "Create your workspace, choose Pro, and test Comvexa for 3 days.": "Erstellen Sie Ihren Arbeitsbereich, wählen Sie Pro und testen Sie Comvexa 3 Tage lang.",
  "After registration you will choose a plan, complete payment setup, and unlock the dashboard modules included in that plan.": "Nach der Registrierung wählen Sie einen Tarif, schließen die Zahlungseinrichtung ab und schalten die im Tarif enthaltenen Dashboard-Module frei.",
});

Object.assign(common.French, {
  "business modules": "modules métier",
  "subscription plans": "forfaits d'abonnement",
  "Pro free trial": "essai gratuit Pro",
  "Global-ready": "Prêt pour le monde entier",
  "Works for teams, branches, and markets worldwide.": "Adapté aux équipes, succursales et marchés partout dans le monde.",
  "Operations-first": "Pensé pour les opérations",
  "Customers, staff, work, invoices, and reports together.": "Clients, personnel, travail, factures et rapports réunis.",
  "Plan controlled": "Contrôlé par forfait",
  "Only unlock the modules included in each subscription.": "Débloque uniquement les modules inclus dans chaque abonnement.",
  "Pro trial": "Essai Pro",
  "Try Pro for 3 days before continuing monthly.": "Essayez Pro pendant 3 jours avant de continuer au mois.",
  Basic: "Basique",
  "Essential tools for small businesses and freelancers.": "Outils essentiels pour les petites entreprises et les indépendants.",
  "The best starting point for growing companies with staff.": "Le meilleur point de départ pour les entreprises en croissance avec du personnel.",
  "Full control for companies with branches, stock, and permissions.": "Contrôle complet pour les entreprises avec succursales, stock et permissions.",
  "Customer management": "Gestion des clients",
  "Services/products": "Services/produits",
  "Customer balances": "Soldes clients",
  "Basic reports": "Rapports de base",
  "Company settings": "Paramètres de l'entreprise",
  "Everything in Basic": "Tout dans Basique",
  "Employee management": "Gestion des employés",
  "Staff schedules": "Plannings du personnel",
  "Documents and PDF uploads": "Documents et téléversements PDF",
  "Recurring invoices": "Factures récurrentes",
  "Payment reminders": "Rappels de paiement",
  "WhatsApp templates": "Modèles WhatsApp",
  "Profit and loss summary": "Résumé des profits et pertes",
  "Advanced reports": "Rapports avancés",
  "Everything in Pro": "Tout dans Pro",
  "Multiple branches": "Plusieurs succursales",
  "Inventory management": "Gestion de l'inventaire",
  "Supplier bills": "Factures fournisseurs",
  "Advanced permissions": "Permissions avancées",
  "Payment reconciliation": "Rapprochement des paiements",
  "Multi-currency records": "Enregistrements multi-devises",
  "Custom tax settings": "Paramètres fiscaux personnalisés",
  "Priority support": "Support prioritaire",
  "Can Comvexa work for any industry?": "Comvexa convient-il à tous les secteurs ?",
  "Is company data separated?": "Les données d'entreprise sont-elles séparées ?",
  "Does Comvexa include accounting tools?": "Comvexa inclut-il des outils comptables ?",
  "Which plan has a free trial?": "Quel forfait inclut un essai gratuit ?",
  "Yes. Comvexa is designed as a flexible company management platform for service businesses, retailers, agencies, clinics, contractors, and many other operating teams.": "Oui. Comvexa est conçu comme une plateforme flexible de gestion d'entreprise pour les services, commerces, agences, cliniques, entrepreneurs et de nombreuses équipes opérationnelles.",
  "Yes. Company records are separated by workspace so each business can only access its own data when security rules are applied.": "Oui. Les données d'entreprise sont séparées par espace de travail afin que chaque entreprise n'accède qu'à ses propres données lorsque les règles de sécurité sont appliquées.",
  "Comvexa includes invoices, payments, expenses, supplier bills, tax tracking fields, receivables, cash flow, and profit/loss summaries. It is built for operational accounting workflows.": "Comvexa inclut factures, paiements, dépenses, factures fournisseurs, champs de suivi fiscal, créances, trésorerie et résumés de profits et pertes. Il est conçu pour les workflows de comptabilité opérationnelle.",
  "Only Pro includes a free trial, and the trial lasts 3 days. Basic and Ultra do not include a free trial.": "Seul Pro inclut un essai gratuit de 3 jours. Basique et Ultra n'incluent pas d'essai gratuit.",
  "Create company workspace": "Créer l'espace de l'entreprise",
  "Register, choose a plan, complete payment setup.": "Inscrivez-vous, choisissez un forfait et terminez la configuration du paiement.",
  "Add business data": "Ajouter les données métier",
  "Customers, employees, services, invoices, tasks, and documents.": "Clients, employés, services, factures, tâches et documents.",
  "Run daily operations": "Gérer les opérations quotidiennes",
  "Assign work, schedule bookings, record payments, upload PDFs.": "Assigner le travail, planifier les réservations, enregistrer les paiements et téléverser des PDF.",
  "Review performance": "Analyser la performance",
  "Use reports for income, expenses, cash flow, tasks, and bookings.": "Utilisez les rapports pour les revenus, dépenses, trésorerie, tâches et réservations.",
  "Users sign up first, choose a plan, then continue to payment. Only Pro includes a 3-day free trial.": "Les utilisateurs s'inscrivent d'abord, choisissent un forfait, puis continuent vers le paiement. Seul Pro inclut un essai gratuit de 3 jours.",
  "Every operational table is designed around company isolation. The platform is prepared for global settings, PDF storage, plan-based access, permissions, and future payment automation.": "Chaque table opérationnelle est conçue autour de l'isolation des entreprises. La plateforme est prête pour les paramètres globaux, le stockage PDF, l'accès par forfait, les permissions et l'automatisation future des paiements.",
  "Company-isolated data": "Données isolées par entreprise",
  "Business records are tied to company_id.": "Les enregistrements métier sont liés à company_id.",
  "Global settings": "Paramètres globaux",
  "Currency, timezone, and workspace customization.": "Devise, fuseau horaire et personnalisation de l'espace.",
  "Plan-based modules": "Modules selon le forfait",
  "Users only see modules included in their plan.": "Les utilisateurs ne voient que les modules inclus dans leur forfait.",
  "Secure documents": "Documents sécurisés",
  "PDFs can be stored in private company file storage.": "Les PDF peuvent être stockés dans un espace privé de fichiers d'entreprise.",
  "Start with your company workspace": "Commencez avec votre espace d'entreprise",
  "Sign up, choose your plan, complete payment setup, then open your dashboard.": "Inscrivez-vous, choisissez votre forfait, terminez la configuration du paiement, puis ouvrez votre tableau de bord.",
  "Comvexa is built step by step so your company can start simple, then expand into accounting, operations, documents, inventory, permissions, and reports.": "Comvexa est construit étape par étape afin que votre entreprise puisse commencer simplement, puis s'étendre à la comptabilité, aux opérations, documents, stocks, permissions et rapports.",
  "Run customers, staff, bookings, invoices, payments, expenses, documents, inventory, branches, permissions, and reports from one professional workspace built for global businesses.": "Gérez clients, personnel, réservations, factures, paiements, dépenses, documents, inventaire, succursales, permissions et rapports depuis un espace professionnel conçu pour les entreprises mondiales.",
  "Company data": "Données d'entreprise",
  "Separated by workspace": "Séparées par espace",
  "3 days included": "3 jours inclus",
  Plans: "Forfaits",
  "Basic, Pro, Ultra": "Basique, Pro, Ultra",
  "Create your workspace, choose Pro, and test Comvexa for 3 days.": "Créez votre espace, choisissez Pro et testez Comvexa pendant 3 jours.",
  "After registration you will choose a plan, complete payment setup, and unlock the dashboard modules included in that plan.": "Après l'inscription, vous choisirez un forfait, terminerez la configuration du paiement et débloquerez les modules du tableau de bord inclus dans ce forfait.",
});

Object.assign(common.Spanish, {
  "business modules": "módulos de negocio",
  "subscription plans": "planes de suscripción",
  "Pro free trial": "prueba gratuita Pro",
  "Global-ready": "Listo para operar globalmente",
  "Works for teams, branches, and markets worldwide.": "Funciona para equipos, sucursales y mercados de todo el mundo.",
  "Operations-first": "Enfocado en operaciones",
  "Customers, staff, work, invoices, and reports together.": "Clientes, personal, trabajo, facturas e informes en un solo lugar.",
  "Plan controlled": "Controlado por plan",
  "Only unlock the modules included in each subscription.": "Desbloquea solo los módulos incluidos en cada suscripción.",
  "Pro trial": "Prueba Pro",
  "Try Pro for 3 days before continuing monthly.": "Prueba Pro durante 3 días antes de continuar mensualmente.",
  Basic: "Básico",
  "Essential tools for small businesses and freelancers.": "Herramientas esenciales para pequeñas empresas y autónomos.",
  "The best starting point for growing companies with staff.": "El mejor punto de partida para empresas en crecimiento con personal.",
  "Full control for companies with branches, stock, and permissions.": "Control total para empresas con sucursales, inventario y permisos.",
  "Customer management": "Gestión de clientes",
  "Services/products": "Servicios/productos",
  "Customer balances": "Saldos de clientes",
  "Basic reports": "Informes básicos",
  "Company settings": "Configuración de empresa",
  "Everything in Basic": "Todo lo de Básico",
  "Employee management": "Gestión de empleados",
  "Staff schedules": "Horarios del personal",
  "Documents and PDF uploads": "Documentos y carga de PDF",
  "Recurring invoices": "Facturas recurrentes",
  "Payment reminders": "Recordatorios de pago",
  "WhatsApp templates": "Plantillas de WhatsApp",
  "Profit and loss summary": "Resumen de ganancias y pérdidas",
  "Advanced reports": "Informes avanzados",
  "Everything in Pro": "Todo lo de Pro",
  "Multiple branches": "Varias sucursales",
  "Inventory management": "Gestión de inventario",
  "Supplier bills": "Facturas de proveedores",
  "Advanced permissions": "Permisos avanzados",
  "Payment reconciliation": "Conciliación de pagos",
  "Multi-currency records": "Registros en varias monedas",
  "Custom tax settings": "Configuración fiscal personalizada",
  "Priority support": "Soporte prioritario",
  "Can Comvexa work for any industry?": "¿Comvexa sirve para cualquier sector?",
  "Is company data separated?": "¿Los datos de cada empresa están separados?",
  "Does Comvexa include accounting tools?": "¿Comvexa incluye herramientas contables?",
  "Which plan has a free trial?": "¿Qué plan tiene prueba gratuita?",
  "Yes. Comvexa is designed as a flexible company management platform for service businesses, retailers, agencies, clinics, contractors, and many other operating teams.": "Sí. Comvexa está diseñado como una plataforma flexible de gestión empresarial para servicios, comercios, agencias, clínicas, contratistas y muchos otros equipos operativos.",
  "Yes. Company records are separated by workspace so each business can only access its own data when security rules are applied.": "Sí. Los registros de empresa se separan por espacio de trabajo para que cada negocio solo acceda a sus propios datos cuando se aplican las reglas de seguridad.",
  "Comvexa includes invoices, payments, expenses, supplier bills, tax tracking fields, receivables, cash flow, and profit/loss summaries. It is built for operational accounting workflows.": "Comvexa incluye facturas, pagos, gastos, facturas de proveedores, campos de seguimiento fiscal, cuentas por cobrar, flujo de caja y resúmenes de ganancias y pérdidas. Está creado para flujos de contabilidad operativa.",
  "Only Pro includes a free trial, and the trial lasts 3 days. Basic and Ultra do not include a free trial.": "Solo Pro incluye una prueba gratuita de 3 días. Básico y Ultra no incluyen prueba gratuita.",
  "Create company workspace": "Crear espacio de empresa",
  "Register, choose a plan, complete payment setup.": "Regístrate, elige un plan y completa la configuración de pago.",
  "Add business data": "Añadir datos del negocio",
  "Customers, employees, services, invoices, tasks, and documents.": "Clientes, empleados, servicios, facturas, tareas y documentos.",
  "Run daily operations": "Gestionar operaciones diarias",
  "Assign work, schedule bookings, record payments, upload PDFs.": "Asigna trabajo, programa reservas, registra pagos y carga PDF.",
  "Review performance": "Revisar rendimiento",
  "Use reports for income, expenses, cash flow, tasks, and bookings.": "Usa informes de ingresos, gastos, flujo de caja, tareas y reservas.",
  "Users sign up first, choose a plan, then continue to payment. Only Pro includes a 3-day free trial.": "Los usuarios se registran primero, eligen un plan y luego continúan al pago. Solo Pro incluye una prueba gratuita de 3 días.",
  "Every operational table is designed around company isolation. The platform is prepared for global settings, PDF storage, plan-based access, permissions, and future payment automation.": "Cada tabla operativa está diseñada con aislamiento por empresa. La plataforma está preparada para configuración global, almacenamiento de PDF, acceso por plan, permisos y futura automatización de pagos.",
  "Company-isolated data": "Datos aislados por empresa",
  "Business records are tied to company_id.": "Los registros del negocio están vinculados a company_id.",
  "Global settings": "Configuración global",
  "Currency, timezone, and workspace customization.": "Moneda, zona horaria y personalización del espacio.",
  "Plan-based modules": "Módulos según el plan",
  "Users only see modules included in their plan.": "Los usuarios solo ven los módulos incluidos en su plan.",
  "Secure documents": "Documentos seguros",
  "PDFs can be stored in private company file storage.": "Los PDF pueden guardarse en almacenamiento privado de la empresa.",
  "Start with your company workspace": "Empieza con tu espacio de empresa",
  "Sign up, choose your plan, complete payment setup, then open your dashboard.": "Regístrate, elige tu plan, completa la configuración de pago y abre tu panel.",
  "Comvexa is built step by step so your company can start simple, then expand into accounting, operations, documents, inventory, permissions, and reports.": "Comvexa está construido paso a paso para que tu empresa empiece simple y luego crezca hacia contabilidad, operaciones, documentos, inventario, permisos e informes.",
  "Run customers, staff, bookings, invoices, payments, expenses, documents, inventory, branches, permissions, and reports from one professional workspace built for global businesses.": "Gestiona clientes, personal, reservas, facturas, pagos, gastos, documentos, inventario, sucursales, permisos e informes desde un espacio profesional creado para empresas globales.",
  "Company data": "Datos de empresa",
  "Separated by workspace": "Separados por espacio",
  "3 days included": "3 días incluidos",
  Plans: "Planes",
  "Basic, Pro, Ultra": "Básico, Pro, Ultra",
  "Create your workspace, choose Pro, and test Comvexa for 3 days.": "Crea tu espacio, elige Pro y prueba Comvexa durante 3 días.",
  "After registration you will choose a plan, complete payment setup, and unlock the dashboard modules included in that plan.": "Después del registro elegirás un plan, completarás la configuración de pago y desbloquearás los módulos del panel incluidos en ese plan.",
});

Object.assign(common.Arabic, {
  "business modules": "وحدات الأعمال",
  "subscription plans": "خطط الاشتراك",
  "Pro free trial": "تجربة Pro المجانية",
  "Global-ready": "جاهز عالمياً",
  "Works for teams, branches, and markets worldwide.": "يناسب الفرق والفروع والأسواق حول العالم.",
  "Operations-first": "مصمم للعمليات",
  "Customers, staff, work, invoices, and reports together.": "العملاء والموظفون والعمل والفواتير والتقارير في مكان واحد.",
  "Plan controlled": "تحكم حسب الخطة",
  "Only unlock the modules included in each subscription.": "افتح فقط الوحدات المضمنة في كل اشتراك.",
  "Pro trial": "تجربة Pro",
  "Try Pro for 3 days before continuing monthly.": "جرّب Pro لمدة 3 أيام قبل المتابعة شهرياً.",
  Basic: "الأساسية",
  "Essential tools for small businesses and freelancers.": "أدوات أساسية للشركات الصغيرة والمستقلين.",
  "The best starting point for growing companies with staff.": "أفضل بداية للشركات النامية التي لديها موظفون.",
  "Full control for companies with branches, stock, and permissions.": "تحكم كامل للشركات ذات الفروع والمخزون والصلاحيات.",
  "Customer management": "إدارة العملاء",
  "Services/products": "الخدمات/المنتجات",
  "Customer balances": "أرصدة العملاء",
  "Basic reports": "تقارير أساسية",
  "Company settings": "إعدادات الشركة",
  "Everything in Basic": "كل ما في الأساسية",
  "Employee management": "إدارة الموظفين",
  "Staff schedules": "جداول الموظفين",
  "Documents and PDF uploads": "المستندات ورفع ملفات PDF",
  "Recurring invoices": "الفواتير المتكررة",
  "Payment reminders": "تذكيرات الدفع",
  "WhatsApp templates": "قوالب واتساب",
  "Profit and loss summary": "ملخص الربح والخسارة",
  "Advanced reports": "تقارير متقدمة",
  "Everything in Pro": "كل ما في Pro",
  "Multiple branches": "فروع متعددة",
  "Inventory management": "إدارة المخزون",
  "Supplier bills": "فواتير الموردين",
  "Advanced permissions": "صلاحيات متقدمة",
  "Payment reconciliation": "مطابقة المدفوعات",
  "Multi-currency records": "سجلات متعددة العملات",
  "Custom tax settings": "إعدادات ضريبية مخصصة",
  "Priority support": "دعم ذو أولوية",
  "Can Comvexa work for any industry?": "هل تعمل Comvexa لأي قطاع؟",
  "Is company data separated?": "هل بيانات الشركات منفصلة؟",
  "Does Comvexa include accounting tools?": "هل تتضمن Comvexa أدوات محاسبة؟",
  "Which plan has a free trial?": "أي خطة تتضمن تجربة مجانية؟",
  "Yes. Comvexa is designed as a flexible company management platform for service businesses, retailers, agencies, clinics, contractors, and many other operating teams.": "نعم. صُممت Comvexa كمنصة مرنة لإدارة الشركات الخدمية ومتاجر التجزئة والوكالات والعيادات والمقاولين والعديد من فرق التشغيل الأخرى.",
  "Yes. Company records are separated by workspace so each business can only access its own data when security rules are applied.": "نعم. تُفصل سجلات الشركة حسب مساحة العمل حتى يتمكن كل نشاط من الوصول إلى بياناته فقط عند تطبيق قواعد الأمان.",
  "Comvexa includes invoices, payments, expenses, supplier bills, tax tracking fields, receivables, cash flow, and profit/loss summaries. It is built for operational accounting workflows.": "تتضمن Comvexa الفواتير والمدفوعات والمصروفات وفواتير الموردين وحقول تتبع الضرائب والذمم المدينة والتدفق النقدي وملخصات الربح والخسارة. وهي مصممة لسير عمل المحاسبة التشغيلية.",
  "Only Pro includes a free trial, and the trial lasts 3 days. Basic and Ultra do not include a free trial.": "تتضمن Pro فقط تجربة مجانية مدتها 3 أيام. لا تتضمن الأساسية وUltra تجربة مجانية.",
  "Create company workspace": "إنشاء مساحة عمل الشركة",
  "Register, choose a plan, complete payment setup.": "سجّل واختر خطة وأكمل إعداد الدفع.",
  "Add business data": "إضافة بيانات العمل",
  "Customers, employees, services, invoices, tasks, and documents.": "العملاء والموظفون والخدمات والفواتير والمهام والمستندات.",
  "Run daily operations": "تشغيل العمليات اليومية",
  "Assign work, schedule bookings, record payments, upload PDFs.": "عيّن العمل وجدول الحجوزات وسجّل المدفوعات وارفع ملفات PDF.",
  "Review performance": "مراجعة الأداء",
  "Use reports for income, expenses, cash flow, tasks, and bookings.": "استخدم التقارير للدخل والمصروفات والتدفق النقدي والمهام والحجوزات.",
  "Users sign up first, choose a plan, then continue to payment. Only Pro includes a 3-day free trial.": "يسجّل المستخدمون أولاً، ثم يختارون خطة ويتابعون إلى الدفع. تتضمن Pro فقط تجربة مجانية لمدة 3 أيام.",
  "Every operational table is designed around company isolation. The platform is prepared for global settings, PDF storage, plan-based access, permissions, and future payment automation.": "كل جدول تشغيلي مصمم حول عزل بيانات الشركة. المنصة جاهزة للإعدادات العالمية وتخزين ملفات PDF والوصول حسب الخطة والصلاحيات وأتمتة الدفع مستقبلاً.",
  "Company-isolated data": "بيانات معزولة حسب الشركة",
  "Business records are tied to company_id.": "سجلات العمل مرتبطة بـ company_id.",
  "Global settings": "إعدادات عالمية",
  "Currency, timezone, and workspace customization.": "العملة والمنطقة الزمنية وتخصيص مساحة العمل.",
  "Plan-based modules": "وحدات حسب الخطة",
  "Users only see modules included in their plan.": "يرى المستخدمون فقط الوحدات المضمنة في خطتهم.",
  "Secure documents": "مستندات آمنة",
  "PDFs can be stored in private company file storage.": "يمكن تخزين ملفات PDF في مساحة ملفات خاصة بالشركة.",
  "Start with your company workspace": "ابدأ بمساحة عمل شركتك",
  "Sign up, choose your plan, complete payment setup, then open your dashboard.": "سجّل، اختر خطتك، أكمل إعداد الدفع، ثم افتح لوحة التحكم.",
  "Comvexa is built step by step so your company can start simple, then expand into accounting, operations, documents, inventory, permissions, and reports.": "تم بناء Comvexa خطوة بخطوة حتى تبدأ شركتك ببساطة، ثم تتوسع إلى المحاسبة والعمليات والمستندات والمخزون والصلاحيات والتقارير.",
  "Run customers, staff, bookings, invoices, payments, expenses, documents, inventory, branches, permissions, and reports from one professional workspace built for global businesses.": "أدر العملاء والموظفين والحجوزات والفواتير والمدفوعات والمصروفات والمستندات والمخزون والفروع والصلاحيات والتقارير من مساحة عمل احترافية واحدة مصممة للشركات العالمية.",
  "Company data": "بيانات الشركة",
  "Separated by workspace": "منفصلة حسب مساحة العمل",
  "3 days included": "3 أيام مضمنة",
  Plans: "الخطط",
  "Basic, Pro, Ultra": "الأساسية، Pro، Ultra",
  "Create your workspace, choose Pro, and test Comvexa for 3 days.": "أنشئ مساحة عملك، اختر Pro، واختبر Comvexa لمدة 3 أيام.",
  "After registration you will choose a plan, complete payment setup, and unlock the dashboard modules included in that plan.": "بعد التسجيل ستختار خطة وتكمل إعداد الدفع وتفتح وحدات لوحة التحكم المضمنة في تلك الخطة.",
});

function readLanguage(): Language {
  try {
    const saved = window.localStorage.getItem("comvexa-workspace-settings");
    const settings = saved ? JSON.parse(saved) : null;
    const language = settings?.language ?? window.localStorage.getItem("comvexa-selected-language");

    if (language === "Arabic" || language === "German" || language === "French" || language === "Spanish") {
      return language;
    }
  } catch {
    return "English";
  }

  return "English";
}

const originalText = new WeakMap<Text, string>();
const originalAttributes = new WeakMap<Element, Record<string, string>>();

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function translateText(value: string, dictionary: Record<string, string>) {
  const trimmed = value.trim();
  const normalized = trimmed.replace(/\s+/g, " ");
  const translated = dictionary[trimmed] ?? dictionary[normalized];

  if (translated) {
    return value.replace(trimmed, translated);
  }

  if (trimmed.length > 40) {
    return value;
  }

  let translatedParts = normalized;
  const entries = Object.entries(dictionary)
    .filter(([source]) => source.length > 2)
    .sort(([left], [right]) => right.length - left.length);

  entries.forEach(([source, target]) => {
    translatedParts = translatedParts.replace(new RegExp(escapeRegExp(source), "g"), target);
  });

  if (translatedParts === normalized) {
    return value;
  }

  return value.replace(trimmed, translatedParts);
}

function shouldSkipElement(element: Element | null) {
  if (!element) {
    return false;
  }

  if (element.closest("[data-no-translate]")) {
    return true;
  }

  return ["SCRIPT", "STYLE", "NOSCRIPT", "TEXTAREA", "OPTION"].includes(element.tagName);
}

function isLiveCurrencyText(value: string) {
  const normalized = value.trim().replace(/\s+/g, " ");

  return /^(USD|KWD|SAR|AED|QAR|BHD|OMR|EUR|GBP|SGD|\$|€|£)/.test(normalized);
}

function applyTranslations(language: Language) {
  const dictionary = language === "English" ? {} : common[language];
  document.documentElement.lang = languageCodes[language];
  document.documentElement.dir = language === "Arabic" ? "rtl" : "ltr";

  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const nodes: Text[] = [];

  while (walker.nextNode()) {
    const node = walker.currentNode as Text;
    const parent = node.parentElement;

    if (!node.textContent?.trim() || shouldSkipElement(parent) || isLiveCurrencyText(node.textContent)) {
      continue;
    }

    nodes.push(node);
  }

  nodes.forEach((node) => {
    if (!originalText.has(node)) {
      originalText.set(node, node.textContent ?? "");
    }

    if (language === "English") {
      originalText.set(node, node.textContent ?? "");
      return;
    }

    const source = originalText.get(node) ?? "";
    node.textContent = translateText(source, dictionary);
  });

  document.querySelectorAll("[placeholder], [aria-label], [title]").forEach((element) => {
    if (!originalAttributes.has(element)) {
      originalAttributes.set(element, {
        placeholder: element.getAttribute("placeholder") ?? "",
        ariaLabel: element.getAttribute("aria-label") ?? "",
        title: element.getAttribute("title") ?? "",
      });
    }

    const source = originalAttributes.get(element);

    if (!source) {
      return;
    }

    if (source.placeholder) {
      element.setAttribute("placeholder", language === "English" ? source.placeholder : translateText(source.placeholder, dictionary));
    }

    if (source.ariaLabel) {
      element.setAttribute("aria-label", language === "English" ? source.ariaLabel : translateText(source.ariaLabel, dictionary));
    }

    if (source.title) {
      element.setAttribute("title", language === "English" ? source.title : translateText(source.title, dictionary));
    }
  });
}

export function GlobalTranslator() {
  useEffect(() => {
    let frame = 0;

    function scheduleTranslate() {
      window.cancelAnimationFrame(frame);
      frame = window.requestAnimationFrame(() => applyTranslations(readLanguage()));
    }

    scheduleTranslate();

    const observer = new MutationObserver(scheduleTranslate);
    observer.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: true,
      attributes: true,
      attributeFilter: ["placeholder", "aria-label", "title"],
    });

    window.addEventListener("storage", scheduleTranslate);
    window.addEventListener("comvexa-settings-change", scheduleTranslate);
    window.addEventListener("comvexa-language-change", scheduleTranslate);

    return () => {
      window.cancelAnimationFrame(frame);
      observer.disconnect();
      window.removeEventListener("storage", scheduleTranslate);
      window.removeEventListener("comvexa-settings-change", scheduleTranslate);
      window.removeEventListener("comvexa-language-change", scheduleTranslate);
    };
  }, []);

  return null;
}
